### ISSUE TITLE
Track particpant IDs 

### ISSUE THREAD

**Issue by salsferrazza** [coralblocks/CoralME#1]
The current `OrderBook` class supports a `clientOrderId`, but not a `clientId`, `mpid`, or `participantId` equivalent. Tracking this information would require storing the `clientOrderId` / `mpid` mapping in an out-of-bound index. 

A concrete feature that would require this tracking is self-match prevention.

**Comment by coralblocks** [comment]
We'll be adding `clientId` so that the matching engine can check and reject _trading-to-self_ scenarios. Thanks, Sal.

**Comment by coralblocks** [comment]
This is released in version 1.5.1. You can refer to [OrderBookNoSelfTradeTest.java](https://github.com/coralblocks/CoralME/blob/main/src/test/java/com/coralblocks/coralme/OrderBookNoSelfTradeTest.java).
